# Generated by Django 4.1.5 on 2023-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Training', 'Training'), ('Nutrition', 'Nutrition'), ('Other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
